version: '3'
volumes:
  data:
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - data:/var/lib/redis